"""user_id na tabela todo

Revision ID: f3436a7f4861
Revises: 3c3123bad85c
Create Date: 2025-05-23 15:40:16.736015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3436a7f4861'
down_revision: Union[str, None] = '3c3123bad85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_todo_user_id_users',  # nome da constraint
            'users',
            ['user_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
